name: coolfit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter

  pedometer: any
  permission_handler: any

  flutter_map: 8.2.2
  geolocator: ^12.0.0
  http: ^1.2.0



  # SQLite
  sqflite: ^2.2.8
  path_provider: ^2.0.14
  # crypto for PBKDF2
  crypto: ^3.0.3
  # secure storage for session
  flutter_secure_storage: ^8.1.0
  # email validator (опционально)
  email_validator: ^2.1.17


  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.1.5+1
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: AllertaStencil
      fonts:
        - asset: assets/fonts/AllertaStencil-Regular.ttf
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Regular.ttf
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 700
